# Generated by Django 5.1.3 on 2024-11-08 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_fname', models.CharField(max_length=50)),
                ('doctor_mname', models.CharField(max_length=50)),
                ('doctor_lname', models.CharField(max_length=50)),
                ('doctor_specialization', models.CharField(max_length=100)),
                ('doctor_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors_mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctors_mobile', models.CharField(max_length=10)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_fname', models.CharField(max_length=50)),
                ('patient_mname', models.CharField(max_length=50)),
                ('patient_lname', models.CharField(max_length=50)),
                ('patient_type_blood', models.CharField(max_length=3)),
                ('patient_dob', models.DateField()),
                ('patient_status', models.CharField(max_length=20)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('patient_status__in', ['Pending', 'Canceled', 'Completed'])), name='check_patient_status')],
            },
        ),
        migrations.CreateModel(
            name='Patient_Historical',
            fields=[
                ('historical_id', models.AutoField(primary_key=True, serialize=False)),
                ('historical_date', models.DateField()),
                ('historical_describe', models.CharField(max_length=1000)),
                ('historical_note', models.CharField(max_length=200)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Addresses',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('patient_state', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_city', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_street', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_number_add', models.CharField(blank=True, max_length=8, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_init_date', models.DateField()),
                ('bill_end_date', models.DateField(blank=True, null=True)),
                ('bill_title', models.CharField(max_length=20)),
                ('bill_description', models.CharField(max_length=30)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('appointment_description', models.CharField(max_length=200)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.doctors')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Patients_mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('treatment_id', models.AutoField(primary_key=True, serialize=False)),
                ('treatment_name', models.CharField(max_length=50)),
                ('treatment_description', models.CharField(max_length=100)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.appointments')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.doctors')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.patients')),
            ],
        ),
    ]
