# Generated by Django 5.1.3 on 2024-11-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors_mobile',
            name='doctors_mobile',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patients_mobile',
            name='patient_mobile',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
