# Generated by Django 5.1.3 on 2024-11-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patients',
            table='website_patients',
        ),
    ]
