# Generated by Django 5.1.3 on 2024-11-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_patients_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patients',
            table=None,
        ),
    ]
