# Generated by Django 5.1.3 on 2024-11-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_doctors_mobile_doctors_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='bill_description',
            field=models.CharField(max_length=50),
        ),
    ]
