# Generated by Django 5.1.3 on 2024-11-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_bills_bill_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='bill_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient_addresses',
            name='patient_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient_addresses',
            name='patient_number_add',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient_addresses',
            name='patient_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient_addresses',
            name='patient_street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient_addresses',
            name='patient_zipcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient_historical',
            name='historical_note',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='treatment_description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='treatment_name',
            field=models.CharField(max_length=100),
        ),
    ]
